const quizData = [
    {
        // Define a dictionary type data with key-value pair
        question:"Points A and B lie on a circle with radius 1, and arc AB has a length of pi/3. What fraction of the circumference of the circle is the length of arc AB?",
        options: ["1/5" ,"1/6" ,"1/4","1/7"],
        answer:"1/6"
    },

    {
        // Define a dictionary type data with key-value pair
        question:"In the xy-plane, the point (p,r)lies on the line with equation y = x+b, where b is a constant. The point with coordinates (2p,5r)lies on the line with equation y = 2x + b. If p≠0, what is the value of r/p?(caculator allowed)",
        options: ["2/5" ,"4/3" ,"3/4","5/2"],
        answer:"3/4"
    },

    {
        // Define a dictionary type data with key-value pair
        question:"If x is the average (arithmetic mean) of m and 9,y is the average of 2m and 15, and z is the average of 3m and 18, what is the average of x,y, and z in terms of m ",
        options: ["m+6" ,"m+7" ,"2m+14","3m+21"],
        answer:"m+7"
    },

    {
        // Define a dictionary type data with key-value pair
        question:"(q=1/2xnv(squared) The dynamic pressure generated by a fluid moving with velocity v can be found using the formula above, where n is the constant density of the fluid. An aeronautical engineer users the formula to find the dynamic pressure of a fluid moving with velocity v and the same fluid moving with velocity 1.5v. What is the ratio of the dynamic pressure of the faster fluid to the dynamic pressure of the slower fluid?",
        options: ["1 4/9" ,"1 1/2" ,"9/4","1 1/4"],
        answer:"9/4"
    },
];

const questionElement = document.getElementById('question');
const startButton = document.getElementById('start-btn');
const resultElement = document.getElementById('result');
const timerElement = document.getElementById('timer');
const timerText = document.getElementById('countdown');
const progressbar = document.getElementById('progress-bar');
const progressBarContainer = document.getElementById('progress-bar-container');
const optionsElement = document.getElementById('option-container');

progressbar.style.width = '0%';

let timer = 0;
let currentQuestion = 0;
let score = 0;


startButton.addEventListener('click', startQuiz);

function startQuiz()
{
    startButton.style.display = 'none';
    progressBarContainer.style.display = 'block';
    resultElement.textContent = `You scored ${score} points`;
    loadQuestion();
}

function loadQuestion()
{
    // reset the timer
    clearInterval(timer);
    
    if(currentQuestion < quizData.length)
    {
        // Update the progress bar
        progressbar.style.width = `${((currentQuestion + 1) / quizData.length) * 100}%`;

        const currentQuizData = quizData[currentQuestion];
        questionElement.textContent = currentQuizData.question;

        // Set initial countdown value
        timerText.textContent = 90; 

        optionsElement.innerHTML = ''; // clear previous options

        // Clone a button for each options in a question
        currentQuizData.options.forEach((option) => {
            const button = document.createElement('button');
            button.textContent = option;
            button.classList.add('option-btn');
            optionsElement.appendChild(button);

            button.addEventListener('click', () => {
                checkAnswer(option);
            });
        });


        // Start the countdown for the current question
        timer = setInterval(() => {
            timerText.textContent = parseInt(timerText.textContent) - 1;
            if(parseInt(timerText.textContent) === 0)
            {
                // reset the timer
                clearInterval(timer);

                currentQuestion = currentQuestion + 1;

                loadQuestion();
            }
        }, 1000);
    } else {
        showResult();
    }
}


function checkAnswer(option)
{
    const currentQuizData = quizData[currentQuestion];

    if(option === currentQuizData.answer)
    {
        score++;
    }

    resultElement.textContent = `You scored ${score} points`;
    currentQuestion++;
    loadQuestion();
}

function showResult()
{
    clearInterval(timer);
    timerElement.style.display = 'none'; // Hide the timer
    progressBarContainer.style.display = 'none';
}